### ISSUE TITLE
Smiley face does not render in Chrome 70

### ISSUE THREAD

**Issue by Tombez** [fuzetsu/minesweeper#1]
![capture](https://user-images.githubusercontent.com/17679570/47894194-ccbb1d00-de1e-11e8-92b5-d3b321c320b7.PNG)

**Comment by Tombez** [comment]
The styled `font-family` is `monospace`, and the actual rendered `font-family` is `Arial`.

**Comment by fuzetsu** [comment]
Interesting, what operating system are you using?
On windows with chrome 70 I see this:
![image](https://user-images.githubusercontent.com/848652/47922193-daa78700-de8c-11e8-9c9b-1c18dbe63768.png)

**Comment by kevino71** [comment]
Works on Chromium Version 69.0.3497.81 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
![screenshot from 2018-11-02 19-08-03](https://user-images.githubusercontent.com/10540846/47944548-a5258c80-ded2-11e8-829c-ecec6bf3f43b.png)

Works on Firefox 62.0.3 (64-bit) on Ubuntu 18.04
![image](https://user-images.githubusercontent.com/10540846/47944587-ec138200-ded2-11e8-9a82-cc173e78661d.png)

**Comment by fuzetsu** [comment]
I might just switch over to using images/css to display the emojis, but I kind of like how it's themed based on what your system provides.. 

Based on @kevino71 's screenshot it looks like having the `font-family` set to `monospace` can change the emoji in certain environments, maybe I'll just wrap the emojis and set the `font-family` to a standard `sans-serif`.

**Comment by Tombez** [comment]
I'm using Windows 7.
I mistakenly thought the rendered `font-family` was `monospace`, but I now realize that makes no sense.

If one scrolls down to the bottom of the "computed" section of the chrome developer tools, it shows the actual rendered font. In my case, it's `Arial`.
What font is being rendered for you? I believe if you load the font that is being displayed for you, and change the css property to `monospace, 'your-rendered-font-here'`, that should prioritize the default font, so both of your pages should look the same before the change, and for systems that don't have a valid font, it should fall back to the one you loaded.

I'm not completely sure about that though, as the MDN page for font-family specifies that a generic font-family name such as `monospace` is supposed to be listed last.

**Comment by fuzetsu** [comment]
I'm thinking that you might not have that emoji in your system.
Can you see the emoji here? https://emojipedia.org/expressionless-face/

Also this is what I see as the rendered font in chrome dev tools: 
![chrome_2018-11-04_18-42-11](https://user-images.githubusercontent.com/848652/47971660-aafda800-e061-11e8-8481-9ded46a943eb.png)

**Comment by Tombez** [comment]
I'm actually having problems getting the emoji characters to display at all, with any font. I've tried `Noto Sans`, even went so far as to install it system-wide, and change all the font settings in chrome to it. Still no luck. What do these look like to you: `😀😗😙😑😮😯😴😛😕😟😦😧😬🕃🕀🕁🕂`?

They're all empty boxes on my computer.

I've come to the conclusion that this issue is exclusive to my computer, so your project probably doesn't need to worry about it.

**Comment by fuzetsu** [comment]
👍 Alright.

This is what I see for the record:
![image](https://user-images.githubusercontent.com/848652/47972092-8a841c80-e066-11e8-9459-550f6e014020.png)
