### ISSUE TITLE
Flags are colored the same color as the number, giving away information.

### ISSUE THREAD

**Issue by Tombez** [fuzetsu/minesweeper#2]
![image](https://user-images.githubusercontent.com/17679570/47972519-e98b6680-e051-11e8-8188-57943501d7ec.png)

**Comment by Tombez** [comment]
![image](https://user-images.githubusercontent.com/17679570/48228940-83595900-e35b-11e8-9ffd-08da72fd1d90.png)

**Comment by fuzetsu** [comment]
Thanks for the report. None of my browsers change the emoji based on css color so I didn't hit this. I'll be making a fix soon!
